 const productsList = [
    {
        id: 1,
        categories: "Эстетический уход",
        subcategory:"Очищение",
        brand: null,
        items: null,
        cashback: 20,
    },
    {
        id: 2,
        categories: "Эстетический уход",
        subcategory:"Скрабы",
        brand: "Academie",
        items: null,
        cashback: 20,
    },
    {
        id: 3,
        categories: "Эстетический уход",
        subcategory:"Очищение",
        brand: "Academie",
        items: "Гоммаж с кремом и витамином У, 50мл",
        cashback: 20,
    },
    {
        id: 4,
        categories: "Эстетический уход",
        subcategory:"Очищение",
        brand: "Academie",
        items: "Нормализующий лосьон, 200мл",
        cashback: 20,
    },
    {
        id: 5,
        categories: "Пилинги",
        subcategory:"Очищение",
        brand: "Frolyis Pro",
        items: "Восстанавливающий уход с кальцием, 50мл",
        cashback: 20,
    },
    {
        id: 6,
        categories: "Средства для коррекции фигуры и массажа ",
        subcategory:"Очищение",
        brand: "Kosmoteros Personnel Paris",
        items: null,
        cashback: 20,
    },
    {
        id: 7,
        categories: "Эстетический уход",
        subcategory:"Очищение",
        brand: null,
        items: null,
        cashback: 20,
    },
    {
        id: 8,
        categories: "Средства для коррекции фигуры и массажа ",
        subcategory:"Очищение",
        brand: null,
        items: null,
        cashback: 20,
    },
    {
        id: 9,
        categories: "Эстетический уход",
        subcategory:"Очищение",
        brand: null,
        items: null,
        cashback: 20,
    },
    {
        id: 10,
        categories: "Пилинги",
        subcategory:"Очищение",
        brand: null,
        items: null,
        cashback: 20,
    },
    {
        id: 11,
        categories: "Эстетический уход",
        subcategory:"Очищение",
        brand: null,
        items: null,
        cashback: 20,
    },
    {
        id: 12,
        categories: "Эстетический уход",
        subcategory:"Очищение",
        brand: null,
        items: null,
        cashback: 20,
    },
    {
        id: 13,
        categories: "Эстетический уход",
        subcategory:"Скрабы",
        brand: "Academie",
        items: null,
        cashback: 20,
    },
    {
        id: 14,
        categories: "Эстетический уход",
        subcategory:"Очищение",
        brand: null,
        items: null,
        cashback: 20,
    },
    {
        id: 15,
        categories: "Эстетический уход",
        subcategory:"Скрабы",
        brand: "Academie",
        items: null,
        cashback: 20,
    },
    {
        id: 16,
        categories: "Эстетический уход",
        subcategory:"Очищение",
        brand: null,
        items: null,
        cashback: 20,
    },
    {
        id: 17,
        categories: "Эстетический уход",
        subcategory:"Скрабы",
        brand: "Academie",
        items: null,
        cashback: 20,
    },
    {
        id: 18,
        categories: "Эстетический уход",
        subcategory:"Очищение",
        brand: null,
        items: null,
        cashback: 20,
    },
    {
        id: 19,
        categories: "Эстетический уход",
        subcategory:"Скрабы",
        brand: "Academie",
        items: null,
        cashback: 20,
    },
    {
        id: 20,
        categories: "Эстетический уход",
        subcategory:"Очищение",
        brand: null,
        items: null,
        cashback: 20,
    },
    {
        id: 21,
        categories: "Эстетический уход",
        subcategory:"Скрабы",
        brand: "Academie",
        items: null,
        cashback: 20,
    },
    {
        id: 22,
        categories: "Эстетический уход",
        subcategory:"Очищение",
        brand: null,
        items: null,
        cashback: 20,
    },
    {
        id: 23,
        categories: "Эстетический уход",
        subcategory:"Скрабы",
        brand: "Academie",
        items: null,
        cashback: 20,
    },
    {
        id: 24,
        categories: "Эстетический уход",
        subcategory:"Очищение",
        brand: null,
        items: null,
        cashback: 20,
    },
    {
        id: 25,
        categories: "Эстетический уход",
        subcategory:"Скрабы",
        brand: "Academie",
        items: null,
        cashback: 20,
    },
    {
        id: 26,
        categories: "Эстетический уход",
        subcategory:"Очищение",
        brand: null,
        items: null,
        cashback: 20,
    },
    {
        id: 27,
        categories: "Эстетический уход",
        subcategory:"Скрабы",
        brand: "Academie",
        items: null,
        cashback: 20,
    },
]
export default productsList;